/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as PassImport } from './routes/pass'

// Create Virtual Routes

const LoginLazyImport = createFileRoute('/login')()
const AccountLazyImport = createFileRoute('/account')()
const IndexLazyImport = createFileRoute('/')()
const SettingsSecurityLazyImport = createFileRoute('/settings/security')()
const GameIdLazyImport = createFileRoute('/game/$id')()

// Create/Update Routes

const LoginLazyRoute = LoginLazyImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/login.lazy').then((d) => d.Route))

const AccountLazyRoute = AccountLazyImport.update({
  path: '/account',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/account.lazy').then((d) => d.Route))

const PassRoute = PassImport.update({
  path: '/pass',
  getParentRoute: () => rootRoute,
} as any)

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const SettingsSecurityLazyRoute = SettingsSecurityLazyImport.update({
  path: '/settings/security',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/settings/security.lazy').then((d) => d.Route),
)

const GameIdLazyRoute = GameIdLazyImport.update({
  path: '/game/$id',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/game/$id.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/pass': {
      id: '/pass'
      path: '/pass'
      fullPath: '/pass'
      preLoaderRoute: typeof PassImport
      parentRoute: typeof rootRoute
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountLazyImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginLazyImport
      parentRoute: typeof rootRoute
    }
    '/game/$id': {
      id: '/game/$id'
      path: '/game/$id'
      fullPath: '/game/$id'
      preLoaderRoute: typeof GameIdLazyImport
      parentRoute: typeof rootRoute
    }
    '/settings/security': {
      id: '/settings/security'
      path: '/settings/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof SettingsSecurityLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/pass': typeof PassRoute
  '/account': typeof AccountLazyRoute
  '/login': typeof LoginLazyRoute
  '/game/$id': typeof GameIdLazyRoute
  '/settings/security': typeof SettingsSecurityLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/pass': typeof PassRoute
  '/account': typeof AccountLazyRoute
  '/login': typeof LoginLazyRoute
  '/game/$id': typeof GameIdLazyRoute
  '/settings/security': typeof SettingsSecurityLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/pass': typeof PassRoute
  '/account': typeof AccountLazyRoute
  '/login': typeof LoginLazyRoute
  '/game/$id': typeof GameIdLazyRoute
  '/settings/security': typeof SettingsSecurityLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/pass'
    | '/account'
    | '/login'
    | '/game/$id'
    | '/settings/security'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/pass' | '/account' | '/login' | '/game/$id' | '/settings/security'
  id:
    | '__root__'
    | '/'
    | '/pass'
    | '/account'
    | '/login'
    | '/game/$id'
    | '/settings/security'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  PassRoute: typeof PassRoute
  AccountLazyRoute: typeof AccountLazyRoute
  LoginLazyRoute: typeof LoginLazyRoute
  GameIdLazyRoute: typeof GameIdLazyRoute
  SettingsSecurityLazyRoute: typeof SettingsSecurityLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  PassRoute: PassRoute,
  AccountLazyRoute: AccountLazyRoute,
  LoginLazyRoute: LoginLazyRoute,
  GameIdLazyRoute: GameIdLazyRoute,
  SettingsSecurityLazyRoute: SettingsSecurityLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/pass",
        "/account",
        "/login",
        "/game/$id",
        "/settings/security"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/pass": {
      "filePath": "pass.tsx"
    },
    "/account": {
      "filePath": "account.lazy.tsx"
    },
    "/login": {
      "filePath": "login.lazy.tsx"
    },
    "/game/$id": {
      "filePath": "game/$id.lazy.tsx"
    },
    "/settings/security": {
      "filePath": "settings/security.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
