on:
  push:
    # Sequence of patterns matched against refs/tags
    branches: [release]
  workflow_dispatch:

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set Release Name
        id: set_release_name
        run: echo "RELEASE_NAME=JastGallery $(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, no need to create your own token
        with:
          tag_name: ${{ github.ref_name }}
          release_name: ${{ env.RELEASE_NAME }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false
