on:
  push:
    branches: [release]
  workflow_dispatch:

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set Release Name
        id: set_release_name
        run: echo "RELEASE_NAME=JastGallery $(date +'%Y-%m-%d')" >> $GITHUB_ENV

      # Extract the version from package.json
      - name: Get package version
        id: get_version
        run: |
          VERSION=$(jq -r '.version' package.json)
          echo "PACKAGE_VERSION=$VERSION" >> $GITHUB_ENV

      # Create a new tag based on the package version
      - name: Create new tag based on package version
        id: create_tag
        run: |
          git tag v${{ env.PACKAGE_VERSION }}
          git push origin v${{ env.PACKAGE_VERSION }}

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ env.PACKAGE_VERSION }}  # Use the package version as the tag
          release_name: ${{ env.RELEASE_NAME }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false
